# -*- coding: utf-8 -*-
"""Proyek Datamining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhgjRBlUHrKAIdQFyLS8IrtyDQjhQhqF
"""

# prompt: give me a code to load dataset. csv from google drive

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Set options to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Assuming 'df' is your DataFrame loaded from the previous step
# Display the entire DataFrame
display(df)